# Generated by Django 5.0.1 on 2024-02-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='student_files/'),
        ),
    ]
